[workspace]
resolver = "3"
members = [
    "packages/cartography",
    "packages/cartography-macros",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Cameron Eldridge <cameldridge@gmail.com>"]
