[package]
name = "cartography"
version = "0.1.0"
authors = ["Cameron Eldridge <cameldridge@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.7.1", features = ["router", "fullstack"] }
futures = "0.3.31"
serde = { version = "1.0.228", features = ["derive"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio", "postgres"], optional = true }
tokio = { version = "1.49.0", features = ["macros"] }
tokio-stream = "0.1.18"
tracing = "0.1.44"

[features]
default = ["web", "server"]
web = ["dioxus/web", "tokio/rt"]
desktop = ["dioxus/desktop", "tokio/rt"]
mobile = ["dioxus/mobile", "tokio/rt"]
server = ["dioxus/server", "tokio/rt-multi-thread", "dep:sqlx"]
