[package]
name = "cartography-macros"
description = """
Cartography macros (internal usage only).
"""
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
hex = "0.4.3"
proc-macro2 = "1.0.106"
quote = "1.0.44"
regex = "1.12.3"
syn = "2.0.115"
